//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIRECCION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DIRECCION()
        {
            this.PROVEEDOR = new HashSet<PROVEEDOR>();
            this.USUARIO = new HashSet<USUARIO>();
        }
    
        public decimal ID { get; set; }
        public string CALLE { get; set; }
        public string NUMERO { get; set; }
        public string PISO { get; set; }
        public string DEPARTAMENTO { get; set; }
        public string OTRO { get; set; }
        public decimal PAIS_ID { get; set; }
        public decimal COMUNA_ID { get; set; }
        public decimal CIUDAD_ID { get; set; }
    
        public virtual CIUDAD CIUDAD { get; set; }
        public virtual COMUNA COMUNA { get; set; }
        public virtual PAIS PAIS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROVEEDOR> PROVEEDOR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USUARIO> USUARIO { get; set; }
    }
}
