//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALC
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Entidades : DbContext
    {
        public Entidades()
            : base("name=Entidades")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TIPO_USUARIO> TIPO_USUARIO { get; set; }
        public virtual DbSet<USUARIO> USUARIO { get; set; }
        public virtual DbSet<USUARIO_ESTADO> USUARIO_ESTADO { get; set; }
    
        public virtual int PROC_I_USUARIO(string p_RUT, string p_NOMBRE, string p_APPATERNO, string p_APMATERNO, string p_CORREO, string p_CONTRASENA, Nullable<decimal> p_TELEFONO, Nullable<decimal> p_TIPO)
        {
            var p_RUTParameter = p_RUT != null ?
                new ObjectParameter("P_RUT", p_RUT) :
                new ObjectParameter("P_RUT", typeof(string));
    
            var p_NOMBREParameter = p_NOMBRE != null ?
                new ObjectParameter("P_NOMBRE", p_NOMBRE) :
                new ObjectParameter("P_NOMBRE", typeof(string));
    
            var p_APPATERNOParameter = p_APPATERNO != null ?
                new ObjectParameter("P_APPATERNO", p_APPATERNO) :
                new ObjectParameter("P_APPATERNO", typeof(string));
    
            var p_APMATERNOParameter = p_APMATERNO != null ?
                new ObjectParameter("P_APMATERNO", p_APMATERNO) :
                new ObjectParameter("P_APMATERNO", typeof(string));
    
            var p_CORREOParameter = p_CORREO != null ?
                new ObjectParameter("P_CORREO", p_CORREO) :
                new ObjectParameter("P_CORREO", typeof(string));
    
            var p_CONTRASENAParameter = p_CONTRASENA != null ?
                new ObjectParameter("P_CONTRASENA", p_CONTRASENA) :
                new ObjectParameter("P_CONTRASENA", typeof(string));
    
            var p_TELEFONOParameter = p_TELEFONO.HasValue ?
                new ObjectParameter("P_TELEFONO", p_TELEFONO) :
                new ObjectParameter("P_TELEFONO", typeof(decimal));
    
            var p_TIPOParameter = p_TIPO.HasValue ?
                new ObjectParameter("P_TIPO", p_TIPO) :
                new ObjectParameter("P_TIPO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_I_USUARIO", p_RUTParameter, p_NOMBREParameter, p_APPATERNOParameter, p_APMATERNOParameter, p_CORREOParameter, p_CONTRASENAParameter, p_TELEFONOParameter, p_TIPOParameter);
        }
    }
}
