//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class PEDIDO
    {
        public decimal ID { get; set; }
        public decimal RESERVA_ID { get; set; }
        public decimal MENU_ID { get; set; }
        public decimal ESTADO_ID { get; set; }
        public System.DateTime CREATED_AT { get; set; }
        public decimal DETALLE_BOLETA_ID { get; set; }
    
        public virtual DETALLE_BOLETA DETALLE_BOLETA { get; set; }
        public virtual ESTADO ESTADO { get; set; }
        public virtual MENU MENU { get; set; }
        public virtual RESERVA RESERVA { get; set; }
    }
}
