//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTO_SOLICITUD
    {
        public byte PRODUCTO_SOLICITUD_ID { get; set; }
        public byte PRODUCTO_ID { get; set; }
        public byte SOLICITUD_ID_SOLICITUD { get; set; }
    
        public virtual PRODUCTO PRODUCTO { get; set; }
        public virtual SOLICITUD SOLICITUD { get; set; }
    }
}
