//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROVEEDOR
    {
        public decimal ID { get; set; }
        public string NOMBRE { get; set; }
        public string RUN { get; set; }
        public string TELEFONO { get; set; }
        public string CORREO { get; set; }
        public string DESCRIPCION { get; set; }
        public decimal DIRECCION_ID { get; set; }
        public decimal GIRO_ID { get; set; }
    }
}
