//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESERVA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RESERVA()
        {
            this.DETALLE_BOLETA = new HashSet<DETALLE_BOLETA>();
            this.PEDIDO = new HashSet<PEDIDO>();
        }
    
        public decimal ID { get; set; }
        public string NOMBRE { get; set; }
        public System.DateTime CREATED_AT { get; set; }
        public decimal USUARIO_ID { get; set; }
        public decimal MESA_ID { get; set; }
        public decimal CLIENTE_ID { get; set; }
        public decimal ESTADO_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLE_BOLETA> DETALLE_BOLETA { get; set; }
        public virtual ESTADO ESTADO { get; set; }
        public virtual MESA MESA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PEDIDO> PEDIDO { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
