//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOLICITUD
    {
        public byte ID_SOLICITUD { get; set; }
        public string ASUNTO { get; set; }
        public string MENSAJE { get; set; }
        public byte ESTADO_SOLICITUD { get; set; }
    }
}
