//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        public decimal ID_USUARIO { get; set; }
        public string RUT { get; set; }
        public string NOMBRE { get; set; }
        public string APPATERNO { get; set; }
        public string APMATERNO { get; set; }
        public string CORREO { get; set; }
        public string CONTRASENA { get; set; }
        public Nullable<decimal> TELEFONO { get; set; }
        public decimal TIPO { get; set; }
        public decimal ESTADO { get; set; }
        public string DIRECCION { get; set; }
    
        public virtual TIPO_USUARIO TIPO_USUARIO { get; set; }
        public virtual USUARIO_ESTADO USUARIO_ESTADO { get; set; }
    }
}
