//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        public decimal ID { get; set; }
        public string RUN { get; set; }
        public string NOMBRE { get; set; }
        public string APELLIDOS { get; set; }
        public string CORREO { get; set; }
        public string PASSWORD { get; set; }
        public decimal TELEFONO { get; set; }
        public decimal ROL_ID { get; set; }
        public System.DateTime CREATED_AT { get; set; }
        public System.DateTime UPDATE_AT { get; set; }
        public string DIRECCION { get; set; }
    
        public virtual RESERVA RESERVA { get; set; }
    }
}
